export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'ABOUT US',
    headline: '',
    description1: ' CGS Technovation is a four-day online event hosted by a joint group of students from our three student associations at Chittagong Grammar School: the Programming Club, the eSports Club, and the Recreational Club. Throughout the event, students will not only be able to compete against students from other schools in their chosen segment but will also have the opportunity to be inspired by great keynote speakers who have made outstanding contributions in their technical fields.',
    description2: 'Students will be able to interact with each other and sharpen their social skills and most importantly, they will be provided with an incredible experience that will foster their creativity, knowledge, leadership skills, and passion for the interdisciplinary application of technology and that too, completely free of cost.',
    imgStart: false,
    img: require('../../images/Technovation-Logo.png'),
    alt: 'About Us Image',
    darkText: true
};

export const homeObjTwo = {
    id: 'stem',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topline: 'Master Coder',
    headline: 'STEM',
    description1: "Segment: Code Inclusion", 
    description2: 'Type: Submission based',
    description3: " Learning a new language isn’t hard if you know where to start. This segment was created with the intention to help young programmers develop a better understanding of coding. Are you ready, future Master Coders, to experience a new side of programming?",
    imgStart: true,
    img: require('../../images/Master-Coder.png'),
    alt: 'Master Coder Image',
    darkText: false
};
export const homeObjTwo1 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- Plagiarism of code will result in immediate disqualification of the participant.',
    description3: '- The provided code must be unaltered unless the instructions explicitly require the participants to change particular values or parameters.',
    description4: "- There is no size or memory limit to the participant's code.",
    description5: '- Use of open-source libraries are allowed but they must be referenced in the code as well as the write-up.',
    imgStart: false,
    img: require('../../images/Rules.png'),
    alt: 'Master Coder Image',
    darkText: false
};
export const homeObjTwo2 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Instructions',
    headline: '',
    description1: '- Few lines of code will be given to the participants.',
    description2: '- Participants will have to use the lines of code given, to a create program of their own in 48 hours.',
    description3: '- Python 3 will be used as the programming language.',
    description4: '- Participants will also be provided a text-document template with questions and will be required to provide a small write-up based on the questions such as the challenges they faced, how they generated their idea and how their code could be implemented in the real world upon further development.',
    imgStart: true,
    img: require('../../images/Instructions.png'),
    alt: 'Master Coder Image',
    darkText: false
};
export const homeObjTwo3 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Judging Criteria',
    headline: '',
    description1: '- Creativity', 
    description2: '- Efficiency', 
    description3: '- How the code is used', 
    description4: '- Contents of the write-up.',
    description5: '*Participants will be provided with the method of submission at the start of the contest',
    imgStart: false,
    img: require('../../images/Judge.png'),
    alt: 'Master Coder Image',
    darkText: false
};

export const homeObjThree = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "Ace Designers'",
    headline: "STEM",
    description1: 'Segment: 3D Modelling', 
    description2: 'Type - Submission-based.',
    description3: ' Future architects, engineers, and designers, prepare to experience the first taste of your future. The segment, “Ace Designers”, was created in order to allow young creative minds like yours to experience a new medium and allow your creations to take on a new form.',
    imgStart: true,
    img: require("../../images/Ace-Designers'.png"),
    alt: 'Ace Designers Image',
    darkText: true
};
export const homeObjThree1 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Rules',
    headline: "",
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- Participants are only allowed to submit a single model.',
    description3: '- Participants will only be given 72 hours to complete the entire project and submit it.',
    description4: '- The main file of the model needs to be submitted along with an Exported FBX version together with the textures.',
    description5: '- A render of the model must also be submitted.',
    description6: '- The following software are only allowed for modeling: Blender, Autodesk Maya, SketchUP.',
    description7: '- Any TEXTURING software is allowed (if participants wish to use a different software to create textures).',
    description8: '- The maximum texture resolution is 4k.',
    description9: '- The model MUST be UV unwrapped (for Blender, Maya, and SketchUP).',
    description10: '- Downloaded models are not allowed; if caught, the involved participant(s) will be disqualified.',
    description11: '- Low-Poly models are not allowed.',
    description12: '- Screenshots of the progress of the model have to also be provided when asked for by the segment runners within appropriate deadlines through appropriate methods.',
    imgStart: false,
    img: require("../../images/Rules.png"),
    alt: 'Ace Designers Image',
    darkText: true
};
export const homeObjThree2 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topline: 'Instructions',
    headline: "",
    description1: '- Participants will be given a topic and need to make a model on the given topic.',
    description2: '- Participants will be required to compress all the required files (check the rules for more information) as a ZIP/RAR file before submission (this ZIP file B needs to be renamed in the following format: Participant Name_School Name).',
    description3: '- Participants using any Blueprints or sheets need to submit them (this will help the judges make informed decisions about the model; participants may wish to watermark their blueprints.)',
    imgStart: true,
    img: require("../../images/Instructions.png"),
    alt: 'Ace Designers Image',
    darkText: true
};
export const homeObjThree3 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Judging Criteria',
    headline: "",
    description1: '- Overall Mesh quality Topology', 
    description2: '- Efficiency of UV maps', 
    description3: '- Photorealism of the render', 
    description4: '- Efficiency of the model (the amount of vertices, tri etc.)',
    description5: ' *Participants will be provided the method of submission at the start of the contest',
    imgStart: false,
    img: require("../../images/Judge.png"),
    alt: 'Ace Designers Image',
    darkText: true
};

export const homeObjFour = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topline: 'GameJam',
    headline: 'STEM',
    description1: 'Segment: Game Development', 
    description2: 'Type - Submission-based',
    description3: ' Game developers work as a bridge between reality and fantasy as they create fantastical environments that allows the player to feel at home. Find yourself in the shoes of one as you participate for an exhilarating experience!',
    imgStart: true,
    img: require('../../images/GameJam.png'),
    alt: 'GameJam Image',
    darkText: false
};
export const homeObjFour1 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of teams from each school: 3 (up to 3 students per team).',
    description2: '- There are no restrictions on the platform used, i.e. participants will be permitted to use any game development platform (e.g. Unity) or make their own game development platform if they wish to.',
    description3: '- All references and third-party materials, such as characters used, must be open source and all links for the references must be provided on the submissions page.',
    description4: '- Browser based games are not allowed 2D, 3D, Infinite (Procedurally Generated) games are allowed.',
    description5: '- There are no restrictions on the genre of the game as long as it fits with the theme.',
    description6: '- No 18+ content will be allowed in the game.',
    description7: '- Plagiarism is prohibited and will be strictly dealt with.',
    description8: '- Maximum duration for the games should be 30 minutes; unless it is an infinite game.',
    description9: '- Failure to uphold the theme will result in disqualification.',
    imgStart: false,
    img: require('../../images/Rules.png'),
    alt: 'GameJam Image',
    darkText: false
};
export const homeObjFour2 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Instructions',
    headline: '',
    description1: '- Participants will create a game based on a given theme.',
    description2: '- Submissions must be made through itch.io and a GitHub repository containing the source code.',
    description3: '- Participants will be given 72 hours after the theme announcement to make and submit their game, no extra time will be given for submissions.',
    description4: '- Participants must also submit a 90-second trailer about the game.',
    description5: '- The target OS for the game should be Windows 10/11. Mobile games and games for macOS are not allowed.',
    imgStart: true,
    img: require('../../images/Instructions.png'),
    alt: 'GameJam Image',
    darkText: false
};
export const homeObjFour3 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Judging Criteria',
    headline: '',
    description1: '- Gameplay Elements', 
    description2: '- Intuitiveness', 
    description3: '- Level Design', 
    description4: '- Artistic Vision', 
    description5: '- Sound Design', 
    description6: '- Story', 
    description7: '- Content of Trailer',
    description8: ' *Participants will be provided with the method of submission at the start of the contest',
    imgStart: false,
    img: require('../../images/Judge.png'),
    alt: 'GameJam Image',
    darkText: false
};

export const homeObjFive = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'The Perfect UI',
    headline: 'STEM',
    description1: 'Segment Type: Front-end Web Development', 
    description2: 'Type - Submission-based.',
    description3: ' The user interface of a website plays a crucial role in the success of businesses in the 21st century. Frontend web developers, it is your time to show your skills of overwhelming a financial market!',
    imgStart: true,
    img: require('../../images/The-Perfect-UI.png'),
    alt: 'Perfect UI Image',
    darkText: true
};
export const homeObjFive1 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- Only HTML, CSS, and JavaScript may be used.',
    description3: '- You must not minify your code.',
    description4: '- No WordPress or Wix websites will be accepted.',
    description5: '- CSS frameworks such as Tailwind or Bootstrap are not allowed.',
    description6: '- The website has no official limit to how many web pages it can contain but the preferred amount is 6.',
    description7: '- Any rule broken will result in immediate disqualification.',
    description8: '- Usage of animations is not mandatory.',
    description9: '- Screenshots of the progress of the website have to be given through the to-be-provided methods when asked for by the admins.',
    imgStart: false,
    img: require('../../images/Rules.png'),
    alt: 'Perfect UI Image',
    darkText: true
};
export const homeObjFive2 = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Instructions',
    headline: '',
    description1: '- Participants must create a front-end project for a topic given (for example, a service business, a hospital, or a university).', 
    description2: '- Submission must be made through a GitHub repository AND a link from the hosted site.',
    description3: '- Total time for creating the website will be 60 hours after the announcement of the topic.',
    description4: '- GitHub repository should be submitted through the to-be provided methods and should be updated at least twice a day before submission of the website.',
    description5: '- If boilerplate code is being used, a reference must be provided at the footer of the website.',
    description6: ' *Participants will be provided with the method of submission at the start of the contest',
    imgStart: true,
    img: require('../../images/Instructions.png'),
    alt: 'Perfect UI Image',
    darkText: true
};
export const homeObjFive3 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Judging Criteria',
    headline: '',
    description: 'Responsiveness of the website', 
    description2:'- Choice of font, color scheme, alignment, and sizing', 
    description3: '- Content of the website Ease of use by users', 
    description4: '- Organization of the code',
    description5: '*Code with comments will be favored more than those without them',
    imgStart: false,
    img: require('../../images/Judge.png'),
    alt: 'Perfect UI Image',
    darkText: true
};

export const homeObjSix = {
    id: 'business',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topline: 'Ingenious Geniuses',
    headline: 'Business and Recreation',
    description1: 'Segment: Business Proposal', 
    description2: 'Type: Live',
    description3: 'By being persuasive without being relentless, by being bold without being pretentious, you will need to learn how to hold onto more than just the attention of your audience and win this dynamic segment.',
    imgStart: true,
    img: require('../../images/Ingenious-Geniuses.png'),
    alt: 'Ingenious Geniuses Image',
    darkText: false
};
export const homeObjSix1 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Rules',
    headline: '',
    description1: '- Participants are required to be present at their exact allocated time.',
    description2: '- Failure to show up within 1 minute of the allocated time will result in immediate disqualification.',
    description3: '- Participants must immediately notify the segment runner through appropriate discord channels if they are facing any network or technical issues and will hence be unable to show up.',
    description4: '- Requests for time change will be dealt with on a case-by-case basis.',
    description5: '- The business idea needs to be turned into a proposal in a PowerPoint presentation.',
    description6: '- Failure to share a presentation, except due to technical difficulties, will result in a large deduction of points.',
    description7: '- Although the ideas may be very innovative, the proposals are required to be practical. For example, a startup is highly unlikely to receive an initial investment of $10 million.',
    description8: '- The participants are required to explain each and every detail in their proposed business plan to achieve higher points.',
    description9: '- They may include the Source of finance, allocation of the factors of production, profitability, the revenue model, suitability of the business in the chosen region, their USP (if there is one), and the market condition.',
    description10: '- Maximum number of participants from each school: 3.',
    imgStart: false,
    img: require('../../images/Rules.png'),
    alt: 'Ingenious Geniuses Image',
    darkText: false
};
export const homeObjSix2 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Instructions',
    headline: '',
    description1: 'ROUND 1:',
    description2: '- Participants will pitch a business proposal to judges live on Zoom.',
    description3: '- Participants are required to create a PowerPoint presentation and use it to present their ideas during the pitch.',
    description4: '- Participants should start working on their pitch as soon as they receive confirmation of their registration because they will be randomly allocated a particular time in the first two days to pitch their proposal and will not be given further time to prepare.',
    description5: '- Participants will only be allowed to speak for a specific amount of time.',
    description6: '- Further details about time constraints will be released before the competition.',
    description7: '- There will be a Q/A session at the end of the presentation where participants may be asked questions by judges about their proposal.',
    description8: '- Over the span of the competition, there will be representative members of the segment who will be there to help the participants with their proposals and keep a check on their progress through appropriate discord channels.',
    description9: '- Participants are also required to submit their PowerPoint presentation through to-be-announced method by the end of round 1',
    description10: 'ROUND 2:',
    description11: '- Qualified participants will move on to the next round which will be held on the third day of the event.',
    description12: '- The participants will be given a situation and will have to present their proposals accordingly.',
    description13: '- Further details about the second round will be released further in the competition.',
    imgStart: true,
    img: require('../../images/Instructions.png'),
    alt: 'Ingenious Geniuses Image',
    darkText: false
};
export const homeObjSix3 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Judging Criteria',
    headline: '',
    description1: '- Critical thinking', 
    description2: '- Authenticity of the idea Innovation and creativity of the business idea', 
    description3: '- Presentation skills', 
    description4: '- Coherence in the answers to the questions by the panel', 
    description5: '- Choice of font, color scheme, alignment, and sizing in the PowerPoint',
    imgStart: false,
    img: require('../../images/Judge.png'),
    alt: 'Ingenious Geniuses Image',
    darkText: false
};

export const homeObjSeven = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Course Of A Discourse',
    headline: 'Business and Recreation',
    description1: 'Segment: Debate', 
    description2: 'Type: Live.',
    description3: ' There is nothing that cannot be settled without words. Do you stand for or against the opinions of society? Take a stand. Debate it.',
    imgStart: true,
    img: require('../../images/Course-of-a-Discourse.png'),
    alt: 'Course of a Discourse Image',
    darkText: true
};
export const homeObjSeven1 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Instructions',
    headline: '',
    description1: '- Each round of debate will focus on a different motion (topic).',
    description2: '- The motion will be disclosed 5 minutes prior to the beginning of the first speech.',
    description3: '- During the 5- minute preparation time before the round, the participants may speak only to their partner.',
    description4: '- The participants will learn their team’s position in a given round just before the motion is announced.',
    description5: '- Participants will be divided to participate in groups of four teams to participate in a British Parliamentary (BP) round.',
    description6: '- Two teams will represent the Government (in support of the motion) and two teams will represent the Opposition (opposed to the Government and the motion).',
    description7: '- Here are the names of the teams and the individual roles: Opening Government (OG), Prime Minister & Deputy Prime Minister, Opening Opposition (OO) Leader & Deputy Leader of Opposition Closing Government (CG), Member of Government & Government Whip Closing Opposition (CO), Member of Opposition & Opposition Whip',
    description8: '- The Government will open the debate, and the Opposition will deliver the final speech.',
    description9: '- Each speaker can present one 2-minute speech.',
    description10: '- The speeches will proceed in this order: Prime Minister -> Leader of Opposition -> Deputy Prime Minister -> Deputy Leader of Opposition -> Member of Government -> Member of Opposition -> Government Whip -> Opposition Whip.',
    description11: '- All the rounds will be held through Zoom.',
    imgStart: false,
    img: require('../../images/Instructions.png'),
    alt: 'Course of a Discourse Image',
    darkText: true
};
export const homeObjSeven2 = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Stages',
    headline: '',
    description1: 'There will be three stages in this competition:',
    description2: '1) The first round will be the qualifying round, where each speaker will get two minutes of speaking time. In this round, there will be no rebuttals.',
    description3: '2) The second round will be the semi-finals. Each speaker will get two minutes speaking time, and one minute for rebuttals.',
    description4: '3) The final round will contain the best debaters. In this round, there will be two minutes for speaking and one minute for rebuttals.',
    description5: '*Maximum number of participants from each school: 3',
    imgStart: true,
    img: require('../../images/Rules.png'),
    alt: 'Course of a Discourse Image',
    darkText: true
};

export const homeObjEight = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Collaging Words',
    headline: 'Business and Recreation',
    description1: 'Segment: Poetry', 
    description2: 'Type: Submission-based.',
    description3: 'Words that are preserved in the right way. Outlive their creators by centuries. Join us, as we immortalize what we wish to say at the moment, on papers that will live on with our own legacy.',
    imgStart: false,
    img: require('../../images/Collaging-Words.png'),
    alt: 'Collaging Words Image',
    darkText: false
};
export const homeObjEight1 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- The pages or articles will be given at random.',
    description3: '- Rhyming scheme is not required.',
    description4: '- Appropriate use of words is encouraged.',
    description5: '- Plagiarized work will be disqualified immediately.',
    description6: '- Any rule broken will result in immediate disqualification.',
    imgStart: true,
    img: require('../../images/Rules.png'),
    alt: 'Collaging Words Image',
    darkText: false
};
export const homeObjEight2 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Instructions',
    headline: '',
    description1: '- The contestants will be given a page from a book or an article generated by a given website.',
    description2: '- They will block out words (similar to blacking out the words), in order to come up with their very own poetry or a story.',
    description3: '- Participants must use the given website.',
    description4: '- Submission should be done through the given method by sharing the link to the finished work or taking a screenshot of the poem.',
    imgStart: false,
    img: require('../../images/Instructions.png'),
    alt: 'Collaging Words Image',
    darkText: false
};
export const homeObjEight3 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Judging Criteria',
    headline: '',
    description1: '- Vividness of the idea of the poetry', 
    description2: '- Relevance to the topic of the poem', 
    description3: '- Proper usage of words',
    imgStart: true,
    img: require('../../images/Judge.png'),
    alt: 'Collaging Words Image',
    darkText: false
};

export const homeObjNine = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'Poster Picasso',
    headline: 'Business and Recreation',
    description1: 'Segment: Digital Arts', 
    description2: 'Type: Submission-based.',
    description3: ' For the creative minds that struggle with traditional art forms, and for the artists who do not wish to go back to a world without an “undo” button, may the works of art you create become masterpieces.',
    imgStart: false,
    img: require('../../images/Poster-Picasso.png'),
    alt: 'Poster Picasso Image',
    darkText: true
};
export const homeObjNine1 = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- Plagiarism will result in immediate disqualification.',
    description3: '- Participants can make use of any application of their choice.',
    description4: '- Participants must include all the given elements in their poster.',
    description5: '- Participants may wish to make use of royalty-free third-party elements.',
    description6: '- They should, however, reference the original creators of the elements through the to-be provided methods',
    imgStart: true,
    img: require('../../images/Rules.png'),
    alt: 'Poster Picasso Image',
    darkText: true
};
export const homeObjNine2 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Instructions',
    headline: '',
    description: '- Participants will be given the topic and the elements on the day the contest starts.',
    description2: '- Participants will use the elements given to make a poster in 72 hours.',
    description3: '- Screenshots of the progress of the website have to be provided through the to-be-provided methods when asked for by the admins.',
    description4: '*Participants will be provided the method of submission of the file(s) at the start of the contest',
    imgStart: false,
    img: require('../../images/Instructions.png'),
    alt: 'Poster Picasso Image',
    darkText: true
};
export const homeObjNine3 = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Judging Criteria',
    headline: '',
    description1: '- Creativity', 
    description2: '- Style', 
    description3: '- Looks', 
    description4: '- Description', 
    description5: '- Use of elements',
    imgStart: true,
    img: require('../../images/Judge.png'),
    alt: 'Poster Picasso Image',
    darkText: true
};

export const homeObjTen = {
    id: 'esports',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Valorant',
    headline: 'eSports',
    description1: 'Type: Live', 
    description2: 'On a stage where competition is present, combine your style and knowledge. You have 13 rounds to use skillful gunplay and tactical prowess to assault and protect your side. Think more quickly than your opponent if you want to live, as you only get one life per round. Take on opponents and prevail!',
    imgStart: false,
    img: require('../../images/Valorant.png'),
    alt: 'Valorant Image',
    darkText: false
};
export const homeObjTen1 = {
    id: 'segments',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Rules',
    headline: '',
    description1: '- Maximum number of teams from each school: 3 (5 members + 1 substitute).',
    description2: '- Both teams must join the indicated discord voice channels for tossing, map bans, and server selection.',
    description3: '- Beware of the players you register as we won’t be allowing random unregistered players to play.',
    description4: '- Important announcements and updates will be on our official discord server. Hence, participants are required to join the Server and take their roles.',
    description5: '- Teaming among participants is strictly prohibited, if participants are caught teaming they will be immediately disqualified.',
    imgStart: true,
    img: require('../../images/Rules.png'),
    alt: 'Valorant Image',
    darkText: false
};
export const homeObjTen2 = {
    id: 'segments',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Instructions',
    headline: '',
    description1: '- The event will be a competitive 5v5 valorant tournament.',
    description2: '- The servers will be decided in accordance to both teams’ pings.',
    description3: '- The brackets will be created in random order and not in accordance to ranks.',
    imgStart: false,
    img: require('../../images/Instructions.png'),
    alt: 'Valorant Image',
    darkText: false
};

export const homeObjEleven = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Fortnite',
    headline: 'eSports',
    description1: 'Type: Live', 
    description2: 'Collaborate with allies to survive in an open-world environment by battling other players or fortifying your cover. The last team standing gets to take the Victory Royale their way.',
    imgStart: true,
    img: require('../../images/Fortnite.png'),
    alt: 'Fortnite Image',
    darkText: true
};
export const homeObjEleven1 = {
    id: 'segments',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'Instructions',
    headline: '',
    description1: '- Maximum number of participants from each school: 3.',
    description2: '- Round 1: Participants will compete in the SOLO game mode.',
    description3: '- There will be 3 games.',
    description4: '- The 10 players with the highest point total will move to Round 2.',
    description5: '- Round 2: The player will be competing in zone wars.',
    description6: '- The final two contestants with the greatest points total will advance to the finals.',
    description7: '- Day 3 the final 2 players will be competing in the box fight system of points.',
    imgStart: false,
    img: require('../../images/Instructions.png'),
    alt: 'Fortnite Image',
    darkText: true
};
export const homeObjEleven2 = {
    id: 'segments',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Scoring System',
    headline: '',
    description1: '- Participants in the Top 5 will earn 4 points.',
    description2: '- Participants in the Top 10 will earn 3 points.',
    description3: '- Every 3 kills will earn the participants 2 points.',
    description4: '- Participants in Top 20 will earn one point.',
    imgStart: true,
    img: require('../../images/Rules.png'),
    alt: 'Fortnite Image',
    darkText: true
};

export const homeObjTwelve = {
    id: 'speakers',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'STEPHEN TURBAN',
    headline: 'Here are the lists of our keynote speakers',
    description1: "Presenting one of the most talented personalities in the tech field, Stephen Turban, who is one of our honorable keynote speakers in CGS Technovation 2023. Stephen will be sharing all of his bits of advice and achievements throughout the event.",
    description2: "Some information about him: Stephen Turban is the co-founder and director of Lumiere Education, an initiative to make high-quality research opportunities easily available for students all around the globe. Except for this helpful approach, his intellectual prowess has allowed him to be a Ph.D. student in Organizational Behavior at Harvard Business School and earn a Bachelor of Science (B.S.) Statistics from Harvard University.",
    imgStart: false,
    img: require('../../images/Stephan.png'),
    alt: 'Speakers Image',
    darkText: false
};
export const homeObjThirteen = {
    id: 'speakers',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Sarjeena Maodud',
    headline: '',
    description1: "Introducing Sarjeena Maodud, one of the brightest and most accomplished young individual, who has honored us to be CGS Technovation 2023's final keynote speaker. Don't forget to join CGS Technovation 2023 to learn more about this inspirational woman's life and career as she shares all the details of her inspiring journey.", 
    description2: "Some more information about her: Sarjeena Maodud, a bright student pursuing a master's degree in entrepreneurship at the University of Cambridge, was born in Russia and raised in Bangladesh. She is the brains of Sheraspace, Bangladesh's first tech-enabled interior design platform, which makes the process of interior design simpler and quicker. She is an amazing personality revolutionising the design industry!",
    imgStart: true,
    img: require('../../images/Sarjeena.png'),
    alt: 'Speakers Image',
    darkText: true
};
export const homeObjFourteen = {
    id: 'speakers',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'SALMAN SAAFI',
    headline: '',
    description1: "Finally, we would like to introduce Salman Saafi! Salman Saafi is a very versatile person who has created a medium to help people in small businesses all over Bangladesh. He will be the final keynote speaker at CGS Technovation 2023 to share the story behind his accomplishments and his creative project, Bonik. Some more information about him - Founder and CEO of Bonik, Salman Saafi has created a simple portal for people who are passionate and interested in starting a small business in minutes.", 
    description2: "As a result of his academic achievements, he received a Bachelor of Science, Electrical and Electronic Engineering degree from the International Islamic University Chittagong. Apart from that, he is also a very engaging photographer who loves to capture the most wonderful moments of his life.",
    imgStart: false,
    img: require('../../images/Salman.png'),
    alt: 'Speakers Image',
    darkText: true
};

export const homeObjFifteen = {
    id: 'partner',
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topline: 'Partner',
    headline: '',
    description1: "All this wouldn’t be possible without our partner HEXA, so what’s Hexa?", 
    description2: "Hexa is here to bring all your imagination to reality! The company is building an Ed-tech platform to improve the educational experience of over 50 million students worldwide studying under the International British Curriculum. It exists to make International Education more affordable and personalized for students who deserve to get much more than what they are paying for right now!", 
    description3: "Hexa partners with your school to digitize the entire 0/A-Level curriculum to make your learning more effortless! As you use their platform, their cutting-edge technology analyzes your behavior and study patterns to create a highly personalized learning experience. In short, Hexa offers you both highly-quality premium content and learning resources prepared in partnership with your school to ensure you learn exactly the way you like at your own pace!", 
    description4: "Acing your board exam is just the tip of the iceberg in your entire educational journey, and Hexa doesn't want to leave you clueless when you are done dominating those exams. It will introduce an entire ecosystem of products to connect you to the top 1% of students studying at the institutions you aspire to be in and working at the best companies in the entire world. To keep it simple, Hexa is revolutionizing your educational experience so that you can achieve what you are truly capable of and that is - to become the Top 1%.",
    imgStart: true,
    img: require('../../images/Hexa.png'),
    alt: 'Partner Image',
    darkText: false
};

export const homeObjSixteen = {
    id: 'faq',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topline: 'FAQs',
    headline: '',
    description1: '- Is CGS Technovation an online event?', 
    description2: 'Ans: Yes! It is a 4-day long online event featuring amazing keynote speakers and talented competitors!',
    description3: '- Will there be any fees required to participate?', 
    description4: 'Ans: No, the event is completely free of cost so no type of fee is required in order to participate.',
    description5: '- Can a student participate in more than one segment?', 
    description6: 'Ans: Yes, a participant can register for up to 2 segments. Students can, however, participate only in one of the live segments because of the risk of time-clash.',
    imgStart: false,
    img: require('../../images/FAQ.png'),
    alt: 'About Us Image',
    darkText: true
};